language: node_js

node_js:
  - "8"
  - "7"

install:
  - npm i mocha
  - npm i expect
  - npm i nyc -g
  - npm i eslint -g
  - npm i codecov -g

script:
  - eslint .
  - npm run test
  - npm run report-coverage